//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONDATHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONDATHANG()
        {
            this.DONTHANHTOAN = new HashSet<DONTHANHTOAN>();
            this.THONGTINDDH = new HashSet<THONGTINDDH>();
        }
    
        public string MA_DATHANG { get; set; }
        public string MA_NCCAP { get; set; }
        public string LOAISP { get; set; }
        public Nullable<System.DateTime> NGAY_DATHANG { get; set; }
        public Nullable<decimal> GIATIEN { get; set; }
    
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONTHANHTOAN> DONTHANHTOAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THONGTINDDH> THONGTINDDH { get; set; }
    }
}
