//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoHang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DONTHANHTOAN
    {
        public string MATT { get; set; }
        public string MA_NCCAP { get; set; }
        public string MA_DATHANG { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        public string TENSP { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        public Nullable<System.DateTime> NGAYTHANHTOAN { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        public Nullable<int> SOLUONG { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        [DisplayFormat(DataFormatString = "{0:0.###}", ApplyFormatInEditMode = true)]
        public Nullable<decimal> GIACA { get; set; }
    
        public virtual DONDATHANG DONDATHANG { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
