//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANGTON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HANGTON()
        {
            this.BANBAOCAO = new HashSet<BANBAOCAO>();
        }
    
        public string MASP { get; set; }
        public string MA_HANGTON { get; set; }
        public Nullable<decimal> SOLUONG { get; set; }
        public string MOTA_HANGTON { get; set; }
        public Nullable<System.DateTime> NGAYHETHAN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANBAOCAO> BANBAOCAO { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
