//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoHang.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLKHEntities1 : DbContext
    {
        public QLKHEntities1()
            : base("name=QLKHEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BANBAOCAO> BANBAOCAO { get; set; }
        public virtual DbSet<DATVAO> DATVAO { get; set; }
        public virtual DbSet<DONDATHANG> DONDATHANG { get; set; }
        public virtual DbSet<DONTHANHTOAN> DONTHANHTOAN { get; set; }
        public virtual DbSet<HANGTON> HANGTON { get; set; }
        public virtual DbSet<KEHANG> KEHANG { get; set; }
        public virtual DbSet<NHACUNGCAP> NHACUNGCAP { get; set; }
        public virtual DbSet<SANPHAM> SANPHAM { get; set; }
    }
}
