//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGTINBAOCAO
    {
        public string MASP { get; set; }
        public string MA_BAOCAO { get; set; }
        public string TENSP { get; set; }
        public Nullable<int> SOLUONG { get; set; }
    
        public virtual BANBAOCAO BANBAOCAO { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
